name: Failure workflow

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Execute Python
      run: python empty.py
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Display
      run: echo 'Le job precedent a echoue'




