name: Condition

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Print test
      run: |
        echo "Job Test"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Print test
      run: |
        echo "Job Deploy"

    - name: Print test
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Job Deploy"
