name: Repository secret Test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    environment : test
    steps:
    - name: Afficher secrets et variables
      run: |
            echo "Variable : ${{ vars.MY_VAR }}"




  
